USE [master]
GO

/****** Object:  Database [TyTestDev_Log]    Script Date: 03/14/2012 22:04:02 ******/
CREATE DATABASE [TyTestDev_Log] ON  PRIMARY 
( NAME = N'TyTestDev_Log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\TyTestDev_Log.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'TyTestDev_Log_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\TyTestDev_Log_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [TyTestDev_Log] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TyTestDev_Log].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TyTestDev_Log] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TyTestDev_Log] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TyTestDev_Log] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TyTestDev_Log] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TyTestDev_Log] SET ARITHABORT OFF 
GO

ALTER DATABASE [TyTestDev_Log] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TyTestDev_Log] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [TyTestDev_Log] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TyTestDev_Log] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TyTestDev_Log] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TyTestDev_Log] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TyTestDev_Log] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TyTestDev_Log] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TyTestDev_Log] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TyTestDev_Log] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TyTestDev_Log] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TyTestDev_Log] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TyTestDev_Log] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TyTestDev_Log] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TyTestDev_Log] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TyTestDev_Log] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TyTestDev_Log] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TyTestDev_Log] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TyTestDev_Log] SET  READ_WRITE 
GO

ALTER DATABASE [TyTestDev_Log] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TyTestDev_Log] SET  MULTI_USER 
GO

ALTER DATABASE [TyTestDev_Log] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TyTestDev_Log] SET DB_CHAINING OFF 
GO


